# Title and theme of portfolio webpage.
title: Casey Bray
logo: "/images/Portfolio_photo.jpg?raw=true"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # Update here to change to a different theme.
